site_name: versort
site_description: Library and command-line utility for sorting versions.
site_url: https://versort.readthedocs.io/
repo_url: https://github.com/Tecnativa/versort
repo_name: Tecnativa/versort

nav:
  - Overview: "index.md"
  # - Creating a template: "creating.md"
  # - Configuring a template: "configuring.md"
  # - Generating a project: "generating.md"
  # - Updating a project: "updating.md"
  # - Reference:
  #     - config:
  #         - factory.py: "reference/config/factory.md"
  #         - objects.py: "reference/config/objects.md"
  #         - user_data.py: "reference/config/user_data.md"
  #     - cli.py: "reference/cli.md"
  #     - main.py: "reference/main.md"
  #     - tools.py: "reference/tools.md"
  #     - types.py: "reference/types.md"
  #     - vcs.py: "reference/vcs.md"
  # - Comparisons: comparisons.md
  # - Contributing: "contributing.md"
  # - Changelog: "changelog.md"

theme:
  name: "material"

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.magiclink
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      watch:
        - versort
